export const USER_ACTION_START = 'USER_ACTION_START';
export const USER_ACTION_FAIL = 'USER_ACTION_FAIL';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const FETCH_ALL_TABLES_SUCCESS = 'FETCH_ALL_TABLES_SUCCESS';
export const FETCH_TABLES_FOR_USER_SUCCESS = 'FETCH_TABLES_FOR_USER_SUCCESS';
export const FETCH_TABLES_FAIL = 'FETCH_TABLES_FAIL';
export const FETCH_TABLES_START = 'FETCH_TABLES_START';

export const FETCH_FREE_PLACES_SUCCESS = 'FETCH_FREE_PLACES_SUCCESS';

export const TICKET_ACTION_START = 'FETCH_TICKETS_START';
export const TICKET_ACTION_FAIL = 'TICKET_ACTION_FAIL';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS';
export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS';

export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAIL = 'FETCH_CUSTOMERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH';
